version: '3.1'
services:
  nessus:
    image: tenable/nessus:latest-ubuntu
    restart: always
    container_name: nessus
#if commented values will be create during first boot and you can change version like Expert, Pro and connect your trial account mail  
#    environment:
#      USERNAME: admin
#      PASSWORD: admin
#      ACTIVATION_CODE: <code>
    ports:
      - 8834:8834

